# [[plugins]]
# repo = 'Shougo/vimshell.vim'
# hook_add = 'nmap [Space]s  <Plug>(vimshell_switch)'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
set helplang& helplang=en,ja
'''

[[plugins]]
repo = 'flowtype/vim-flow'
on_ft = ['javascript', 'javascript.jsx']
hook_add = '''
let g:flow#autoclose = 1
'''
[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']
hook_add = '''
'''
